#!/usr/bin/env bash

set -euo pipefail

export_canva_repo() {
  local origin_url
  local ssm_param
  ssm_param="${BUILDKITE_PLUGIN_GITHUB_FETCH_SSM_PARAM:-}"
  origin_url="$(aws ssm get-parameter --name ${ssm_param} --query \"Parameter.Value\" --output text)"
  export BUILDKITE_REPO="${origin_url}"
}

main() {
  export_buildkite_repo
}

main "$@"